/*
  =========================
  CONFIGURAÇÃO DO SUPABASE
  =========================

  1) Crie um projeto em: https://supabase.com
  2) Vá em Project Settings > API
  3) Copie e cole:
     - SUPABASE_URL (Project URL)
     - SUPABASE_ANON_KEY (anon public key)

  IMPORTANTE:
  - Nunca use Service Role Key no frontend.
  - Use somente a anon key no navegador.
*/
const SUPABASE_URL = "COLE_AQUI_SUA_SUPABASE_URL";
const SUPABASE_ANON_KEY = "COLE_AQUI_SUA_SUPABASE_ANON_KEY";

const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

/*
  =========================
  USUÁRIOS ADMINISTRADORES
  =========================

  Como criar administrador:
  1) No painel Supabase, acesse Authentication > Users
  2) Clique em "Add user" e crie o usuário com e-mail e senha
  3) Adicione o e-mail criado na lista ADMIN_EMAILS abaixo
*/
const ADMIN_EMAILS = ["admin@visaonobre.com.br"];

function isAdminEmail(email) {
  return ADMIN_EMAILS.includes((email || "").toLowerCase().trim());
}

/*
  =========================
  SQL SUGERIDO (executar no Supabase SQL Editor)
  =========================

  create table if not exists public.inscricoes (
    id bigint generated by default as identity primary key,
    nome text not null,
    cpf text not null unique,
    idade int not null,
    nascimento date not null,
    telefone text not null,
    whatsapp text not null,
    email text not null,
    cidade text not null,
    bairro text not null,
    created_at timestamptz default now()
  );

  alter table public.inscricoes enable row level security;

  -- Permite inserir inscrição sem login (site público)
  create policy "insert_public_inscricoes"
  on public.inscricoes
  for insert
  to anon, authenticated
  with check (true);

  -- Permite leitura/deleção apenas autenticado (admin)
  create policy "read_auth_inscricoes"
  on public.inscricoes
  for select
  to authenticated
  using (true);

  create policy "delete_auth_inscricoes"
  on public.inscricoes
  for delete
  to authenticated
  using (true);
*/
